/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'gareth' at '01/03/14 19:28' with Gradle 1.10
 *
 * @author gareth, @date 01/03/14 19:28
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
