/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'gareth' at '01/03/14 19:28' with Gradle 1.10
 *
 * @author gareth, @date 01/03/14 19:28
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
